language: java
sudo: required
addons: 
 sonarcloud:
    organization: "oxygenxml-github"
    token:
      secure: "${SONAR_CLOUD_TOKEN}"

dist: trusty
jdk:
 - oraclejdk8
cache:
  directories:
  - $HOME/.m2
matrix:
  fast_finish: true
install: true
before_script:
  - chmod +x travis/deploy.sh
  - chmod +x travis/checkForTag.sh
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${PROLOG_TOKEN}:@github.com" > .git/credentials
  - ./travis/checkForTag.sh
script:
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
before_deploy:
  - ./travis/deploy.sh
deploy:
  provider: releases
  api_key: ${PROLOG_TOKEN}
  file:
    - target/oxygen-dita-prolog-updater-${TRAVIS_TAG}-plugin.jar
    - target/addon.xml
  skip_cleanup: true
  on:
    tags: true
